name: Android CI

on:
 push:
  branches:
   - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint debug flavor
        run: bash ./gradlew lintDebug --stacktrace
      - name: Lint results
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/reports/lint-results-debug.html
